server.port: 8084

spring:
  application:
    name: store-service
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: info
    com.c9pay.storeservice: debug
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

jwt:
  service-type: store
  secret: REVGQVVMVERFRkFVTFRERUZBVUxUREVGQVVMVERFRkFVTFRERUZBVUxUREVGQVVMVERFRkFVTFRERUZBVUxUREVGQVVMVA==
  token-validity-in-seconds: 86400 # 24시간



management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3, w3c
      produce: b3, w3c
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
